create table if not exists public.vgg_inventory_snapshots (
  id bigint generated by default as identity primary key,
  link_id bigint null references public.vgg_links (id) on delete set null,
  event_id text not null,
  event_url text not null,
  captured_at timestamptz not null,
  snapshot_json jsonb not null,
  summary_json jsonb not null,
  source text not null default 'event_page_json',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_vgg_inventory_snapshots_event_id_captured_at
  on public.vgg_inventory_snapshots (event_id, captured_at desc);

create index if not exists idx_vgg_inventory_snapshots_link_id_captured_at
  on public.vgg_inventory_snapshots (link_id, captured_at desc);

create index if not exists idx_vgg_inventory_snapshots_event_url_captured_at
  on public.vgg_inventory_snapshots (event_url, captured_at desc);

create table if not exists public.vgg_inventory_diffs (
  id bigint generated by default as identity primary key,
  snapshot_id bigint null references public.vgg_inventory_snapshots (id) on delete cascade,
  previous_snapshot_id bigint null references public.vgg_inventory_snapshots (id) on delete set null,
  event_id text not null,
  captured_at timestamptz not null,
  change_count integer not null,
  diff_json jsonb not null,
  alert_sent boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_vgg_inventory_diffs_event_id_captured_at
  on public.vgg_inventory_diffs (event_id, captured_at desc);

create index if not exists idx_vgg_inventory_diffs_snapshot_id
  on public.vgg_inventory_diffs (snapshot_id);

grant usage on schema public to service_role;

grant select, insert, update, delete on table public.vgg_inventory_snapshots to service_role;
grant select, insert, update, delete on table public.vgg_inventory_diffs to service_role;

grant usage, select on sequence public.vgg_inventory_snapshots_id_seq to service_role;
grant usage, select on sequence public.vgg_inventory_diffs_id_seq to service_role;
